kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: orkivar-pdfgen
  namespace: dab
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
  labels:
    team: dab
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 608Mi
    requests:
      cpu: 485m
      memory: 544Mi
  accessPolicy:
    inbound:
      rules:
        - application: orkivar
          namespace: dab
          cluster: prod-gcp
  env:
      - name: _JAVA_OPTIONS
        value: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0"