kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: orkivar-pdfgen
  namespace: dab
  labels:
    team: dab
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/is_alive
  readiness:
      path: /internal/is_ready
  startup:
    path: /internal/is_alive
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 768Mi
  accessPolicy:
    inbound:
      rules:
        - application: orkivar
          namespace: dab
          cluster: dev-gcp