name: Deploy ORKIVAR-PDFGEN main branch to dev and prod
run-name:  Deploy ORKIVAR-PDFGEN main branch to dev and prod by @${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy_prod_and_dev
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  dev:
    needs: build
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env: dev
      image: ${{ needs.build.outputs.image }}
  prod:
    needs: build
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      env: prod
      image: ${{ needs.build.outputs.image }}
