name: Build, push, and deploy

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nais/deploy/actions/deploy@v3
        env:
          CLUSTER: ${{ inputs.env }}-gcp
          RESOURCE: nais/nais-${{ inputs.env }}.yaml
          VAR: image=${{ inputs.image }}